[package]
name = "basketui"
version = "0.1.0"
edition = "2021"
description = "A terminal UI for browsing NBA games from the balldontlie API"
license = "MIT"
repository = "https://github.com/amdiazzz/basketui"
homepage = "https://github.com/amdiazzz/basketui"
keywords = ["tui", "nba", "basketball", "terminal", "ratatui", "balldontlie"]
categories = ["command-line-utilities", "user-interface"]
authors = ["Alex Diaz <amdiazzz@users.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.29.0"
line-clipping = "0.3.7"
ratatui = "0.30.0"
chrono = "0.4"
json = "0.12.4"
reqwest = { version = "0.13.3", features = ["json"] }
tokio = { version = "1.52.3", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0.228", features = ["derive"] }
dotenvy = "0.15.7"
